[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
hex = "0.4.3"
network-interface = "2.0.0"
nix = { version = "0.29.0", features = ["socket"] }
rand = "0.8.5"
thiserror = "1.0.64"

[dev-dependencies]
rayon = "1.10.0"
